export const genres = [
  { value: 'hanh-dong', label: 'Hành động' },
  { value: 'tinh-cam', label: 'Tình cảm' },
  { value: 'hai-huoc', label: 'Hài hước' },
  { value: 'co-trang', label: 'Cổ trang' },
  { value: 'tam-ly', label: 'Tâm lý' },
  { value: 'hinh-su', label: 'Hình Sự' },
  { value: 'chien-tranh', label: 'Chiến tranh' },
  { value: 'the-thao', label: 'Thể thao' },
  { value: 'vo-thuat', label: 'Võ thuật' },
  { value: 'vien-tuong', label: 'Viễn tưởng' },
  { value: 'phieu-luu', label: 'Phiêu lưu' },
  { value: 'khoa-hoc', label: 'Khoa học' },
  { value: 'kinh-di', label: 'Kinh dị' },
  { value: 'am-nhac', label: 'Âm nhạc' },
  { value: 'than-thoai', label: 'Thần thoại' },
  { value: 'tai-lieu', label: 'Tài liệu' },
  { value: 'gia-dinh', label: 'Gia đình' },
  { value: 'chinh-kich', label: 'Chính kịch' },
  { value: 'bi-an', label: 'Bí ẩn' },
  { value: 'hoc-duong', label: 'Học đường' },
  { value: 'kinh-dien', label: 'Kinh điển' },
  { value: 'phim-18', label: 'Phim 18+' },
];

export const countries = [
  { value: 'trung-quoc', label: 'Trung Quốc' },
  { value: 'han-quoc', label: 'Hàn Quốc' },
  { value: 'nhat-ban', label: 'Nhật Bản' },
  { value: 'thai-lan', label: 'Thái Lan' },
  { value: 'au-my', label: 'Âu Mỹ' },
  { value: 'dai-loan', label: 'Đài Loan' },
  { value: 'hong-kong', label: 'Hồng Kông' },
  { value: 'an-do', label: 'Ấn Độ' },
  { value: 'anh', label: 'Anh' },
  { value: 'phap', label: 'Pháp' },
  { value: 'canada', label: 'Canada' },
  { value: 'quoc-gia-khac', label: 'Quốc Gia Khác' },
  { value: 'duc', label: 'Đức' },
  { value: 'tay-ban-nha', label: 'Tây Ban Nha' },
  { value: 'tho-nhi-ky', label: 'Thổ Nhĩ Kỳ' },
  { value: 'ha-lan', label: 'Hà Lan' },
  { value: 'indonesia', label: 'Indonesia' },
  { value: 'nga', label: 'Nga' },
  { value: 'mexico', label: 'Mexico' },
  { value: 'ba-lan', label: 'Ba Lan' },
  { value: 'uc', label: 'Úc' },
  { value: 'thuy-dien', label: 'Thụy Điển' },
  { value: 'malaysia', label: 'Malaysia' },
  { value: 'brazil', label: 'Brazil' },
  { value: 'philippines', label: 'Philippines' },
  { value: 'bo-dao-nha', label: 'Bồ Đào Nha' },
  { value: 'y', label: 'Ý' },
  { value: 'dan-mach', label: 'Đan Mạch' },
  { value: 'uae', label: 'UAE' },
  { value: 'na-uy', label: 'Na Uy' },
  { value: 'thuy-si', label: 'Thụy Sĩ' },
  { value: 'chau-phi', label: 'Châu Phi' },
  { value: 'nam-phi', label: 'Nam Phi' },
  { value: 'ukraina', label: 'Ukraina' },
  { value: 'a-rap-xe-ut', label: 'Ả Rập Xê Út' },
  { value: 'bi', label: 'Bỉ' },
  { value: 'ireland', label: 'Ireland' },
  { value: 'colombia', label: 'Colombia' },
  { value: 'phan-lan', label: 'Phần Lan' },
  { value: 'viet-nam', label: 'Việt Nam' },
  { value: 'chile', label: 'Chile' },
  { value: 'hy-lap', label: 'Hy Lạp' },
  { value: 'nigeria', label: 'Nigeria' },
  { value: 'argentina', label: 'Argentina' },
  { value: 'singapore', label: 'Singapore' },
];

export const sortOptions = [
  { value: 'year', label: 'Năm phát hành' },
  { value: 'updated', label: 'Cập nhật lần cuối' },
  { value: 'posted', label: 'Ngày đăng' },
];

export const contentTypes = [
  { value: 'phim-bo', label: 'Phim bộ' },
  { value: 'phim-lẻ', label: 'Phim lẻ' },
  { value: 'hoat-hinh', label: 'Hoạt hình' },
  { value: 'tv-shows', label: 'TV Shows' },
  { value: 'phim-vietsub', label: 'Phim vietsub' },
  { value: 'phim-thuyet-minh', label: 'Phim thuyết minh' },
  { value: 'phim-long-tieng', label: 'Phim lồng tiếng' },
  { value: 'phim-bo-dang-chieu', label: 'Phim bộ đang chiếu' },
  { value: 'phim-bo-hoan-thanh', label: 'Phim bộ hoàn thành' },
  { value: 'phim-sap-chieu', label: 'Phim sắp chiếu' },
  { value: 'subteam', label: 'Subteam' },
];
